defaults: &defaults
  adapter: postgresql
  username: postgres
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  encoding: unicode
  pool: 5
  encoding: utf8


development:
  <<: *defaults
  database: uboxt_dev

test: &test
  <<: *defaults
  database: uboxt_test

production:
  <<: *defaults
  database: uboxt_prod


cucumber:
  <<: *test
